services:
  postgres:
    image: 'postgres:17.5'
    container_name: subtrack_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_LOGIN}
    ports:
      - '5432:5432'
