services:
  postgres:
    image: 'postgres:17.5'
    container_name: subtrack_db
    volumes:
      - subtrack_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_LOGIN}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    image: subtrack-app:0.0.2
    container_name: backend
    ports:
      - "5440:5440"
    environment:
      DB_URL: ${DB_URL}
      DB_LOGIN: ${DB_LOGIN}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      TELEGRAM_BOT_API: ${TELEGRAM_BOT_API}
      TELEGRAM_CREATOR_ID: ${TELEGRAM_CREATOR_ID}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      # JAVA_OPTS: "-Xmx512m -Xms256m"  # Можно переопределить при необходимости
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  subtrack_data: